"""ORM models for persisting analytics artifacts."""

from __future__ import annotations

from datetime import date, datetime
from typing import Any
from uuid import uuid4

from sqlalchemy import Boolean, JSON, Date, DateTime, Float, ForeignKey, Integer, String, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column, relationship

from fomc_analysis.db.base import Base


def _uuid() -> str:
    return str(uuid4())


class DatasetRun(Base):
    """A snapshot of artifacts generated by a pipeline run."""

    __tablename__ = "dataset_runs"
    __table_args__ = (UniqueConstraint("dataset_slug", "run_timestamp", name="uq_dataset_slug_run_ts"),)

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=_uuid)
    run_id: Mapped[str] = mapped_column(String(64), unique=True, default=_uuid, nullable=False)
    dataset_slug: Mapped[str] = mapped_column(String(128), nullable=False)
    dataset_type: Mapped[str] = mapped_column(String(64), nullable=False)
    run_timestamp: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    source_file: Mapped[str | None] = mapped_column(String(512))
    source_hash: Mapped[str | None] = mapped_column(String(128))
    hyperparameters: Mapped[dict[str, Any] | None] = mapped_column(JSON, default=dict)
    metadata_json: Mapped[dict[str, Any] | None] = mapped_column(JSON, default=dict)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=datetime.utcnow)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=datetime.utcnow, onupdate=datetime.utcnow
    )

    overall_metrics: Mapped["OverallMetrics | None"] = relationship(
        back_populates="dataset_run", cascade="all, delete-orphan", uselist=False
    )
    horizon_metrics: Mapped[list["HorizonMetrics"]] = relationship(
        back_populates="dataset_run", cascade="all, delete-orphan"
    )
    predictions: Mapped[list["Prediction"]] = relationship(
        back_populates="dataset_run", cascade="all, delete-orphan"
    )
    trades: Mapped[list["Trade"]] = relationship(
        back_populates="dataset_run", cascade="all, delete-orphan"
    )
    grid_results: Mapped[list["GridSearchResult"]] = relationship(
        back_populates="dataset_run", cascade="all, delete-orphan"
    )


class OverallMetrics(Base):
    """Single-row summary metrics for a run."""

    __tablename__ = "overall_metrics"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=_uuid)
    dataset_run_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("dataset_runs.id", ondelete="CASCADE"), unique=True, nullable=False
    )
    total_trades: Mapped[float | None] = mapped_column(Float)
    total_pnl: Mapped[float | None] = mapped_column(Float)
    roi: Mapped[float | None] = mapped_column(Float)
    win_rate: Mapped[float | None] = mapped_column(Float)
    sharpe: Mapped[float | None] = mapped_column(Float)
    sortino: Mapped[float | None] = mapped_column(Float)
    avg_pnl_per_trade: Mapped[float | None] = mapped_column(Float)
    final_capital: Mapped[float | None] = mapped_column(Float)

    dataset_run: Mapped[DatasetRun] = relationship(back_populates="overall_metrics")


class HorizonMetrics(Base):
    """Metrics tracked per horizon (e.g., 7/14/30 day predictions)."""

    __tablename__ = "horizon_metrics"
    __table_args__ = (UniqueConstraint("dataset_run_id", "horizon_days", name="uq_run_horizon"),)

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=_uuid)
    dataset_run_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("dataset_runs.id", ondelete="CASCADE"), nullable=False
    )
    horizon_days: Mapped[int] = mapped_column(Integer, nullable=False)
    total_predictions: Mapped[int | None] = mapped_column(Integer)
    correct_predictions: Mapped[int | None] = mapped_column(Integer)
    accuracy: Mapped[float | None] = mapped_column(Float)
    total_trades: Mapped[int | None] = mapped_column(Integer)
    winning_trades: Mapped[int | None] = mapped_column(Integer)
    win_rate: Mapped[float | None] = mapped_column(Float)
    total_pnl: Mapped[float | None] = mapped_column(Float)
    avg_pnl_per_trade: Mapped[float | None] = mapped_column(Float)
    roi: Mapped[float | None] = mapped_column(Float)
    sharpe_ratio: Mapped[float | None] = mapped_column(Float)
    brier_score: Mapped[float | None] = mapped_column(Float)

    dataset_run: Mapped[DatasetRun] = relationship(back_populates="horizon_metrics")


class Prediction(Base):
    """Prediction snapshots (historical backtest or live signals)."""

    __tablename__ = "predictions"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=_uuid)
    dataset_run_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("dataset_runs.id", ondelete="CASCADE"), nullable=False
    )
    meeting_date: Mapped[date | None] = mapped_column(Date)
    prediction_date: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    contract: Mapped[str | None] = mapped_column(String(256))
    ticker: Mapped[str | None] = mapped_column(String(128))
    event_ticker: Mapped[str | None] = mapped_column(String(128))
    market_status: Mapped[str | None] = mapped_column(String(64))
    prediction_kind: Mapped[str | None] = mapped_column(String(32))
    days_before_meeting: Mapped[int | None] = mapped_column(Integer)
    days_until_meeting: Mapped[int | None] = mapped_column(Integer)
    predicted_probability: Mapped[float | None] = mapped_column(Float)
    confidence_lower: Mapped[float | None] = mapped_column(Float)
    confidence_upper: Mapped[float | None] = mapped_column(Float)
    market_price: Mapped[float | None] = mapped_column(Float)
    edge: Mapped[float | None] = mapped_column(Float)
    actual_outcome: Mapped[int | None] = mapped_column(Integer)
    correct: Mapped[bool | None] = mapped_column(Boolean)

    dataset_run: Mapped[DatasetRun] = relationship(back_populates="predictions")


class Trade(Base):
    """Executed trades from the backtest."""

    __tablename__ = "trades"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=_uuid)
    dataset_run_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("dataset_runs.id", ondelete="CASCADE"), nullable=False
    )
    meeting_date: Mapped[date | None] = mapped_column(Date)
    prediction_date: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    contract: Mapped[str | None] = mapped_column(String(256))
    ticker: Mapped[str | None] = mapped_column(String(128))
    days_before_meeting: Mapped[int | None] = mapped_column(Integer)
    side: Mapped[str | None] = mapped_column(String(16))
    position_size: Mapped[float | None] = mapped_column(Float)
    entry_price: Mapped[float | None] = mapped_column(Float)
    predicted_probability: Mapped[float | None] = mapped_column(Float)
    edge: Mapped[float | None] = mapped_column(Float)
    actual_outcome: Mapped[int | None] = mapped_column(Integer)
    pnl: Mapped[float | None] = mapped_column(Float)
    roi: Mapped[float | None] = mapped_column(Float)

    dataset_run: Mapped[DatasetRun] = relationship(back_populates="trades")


class GridSearchResult(Base):
    """Parameter sweep results for hyperparameter tuning."""

    __tablename__ = "grid_search_results"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=_uuid)
    dataset_run_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("dataset_runs.id", ondelete="CASCADE"), nullable=False
    )
    total_pnl: Mapped[float | None] = mapped_column(Float)
    roi: Mapped[float | None] = mapped_column(Float)
    sharpe: Mapped[float | None] = mapped_column(Float)
    trades: Mapped[int | None] = mapped_column(Integer)
    win_rate: Mapped[float | None] = mapped_column(Float)
    slippage: Mapped[float | None] = mapped_column(Float)
    transaction_cost_rate: Mapped[float | None] = mapped_column(Float)
    max_position_size: Mapped[float | None] = mapped_column(Float)
    train_window_size: Mapped[int | None] = mapped_column(Integer)
    test_start_date: Mapped[str | None] = mapped_column(String(32))
    yes_position_size_pct: Mapped[float | None] = mapped_column(Float)
    no_position_size_pct: Mapped[float | None] = mapped_column(Float)
    yes_edge_threshold: Mapped[float | None] = mapped_column(Float)
    no_edge_threshold: Mapped[float | None] = mapped_column(Float)

    dataset_run: Mapped[DatasetRun] = relationship(back_populates="grid_results")
